# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8dd740e8ceb749b45edbb36183e9527722401ec8283efbabe5cc7dabcf6811abb3937ff200528ff42c6799824ad57f44b26edc1d7227107d6f17b97625b30a2a

test:
  secret_key_base: b43de6ab21a93eca310b12fd3cdcae91f714a2f172c01590106bffabe7b0023c6bf0a7dfc3a5195259f0131c8f4a75e291597d0c98d59ee21488c308241c6718

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
